Process Process-2:2:
Traceback (most recent call last):
Process Process-4:2:
Traceback (most recent call last):
Process Process-1:2:
Traceback (most recent call last):
  File "/usr/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kk_gorbee/Documents/project/WirelessSensorTrackingSystem/proj/jsonSenderAndReceiver.py", line 39, in receive_message
    server_socket.bind((host, port))
OSError: [Errno 98] Address already in use
  File "/usr/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kk_gorbee/Documents/project/WirelessSensorTrackingSystem/proj/jsonSenderAndReceiver.py", line 39, in receive_message
    server_socket.bind((host, port))
OSError: [Errno 98] Address already in use
  File "/usr/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kk_gorbee/Documents/project/WirelessSensorTrackingSystem/proj/jsonSenderAndReceiver.py", line 39, in receive_message
    server_socket.bind((host, port))
OSError: [Errno 98] Address already in use
Exception ignored in atexit callback: <function _exit_function at 0x7fe6deb44ae0>
Traceback (most recent call last):
  File "/usr/lib/python3.11/multiprocessing/util.py", line 360, in _exit_function
    p.join()
  File "/usr/lib/python3.11/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/multiprocessing/popen_fork.py", line 43, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt: 
Process Process-5:2:
Process Process-3:2:
Process Process-6:2:
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Process Process-4:
Process Process-1:
Process Process-2:
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kk_gorbee/Documents/project/WirelessSensorTrackingSystem/proj/jsonSenderAndReceiver.py", line 43, in receive_message
    conn, addr = server_socket.accept()
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socket.py", line 294, in accept
    fd, addr = self._accept()
               ^^^^^^^^^^^^^^
KeyboardInterrupt
  File "/usr/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
------receiver of 6 is running-------- 
  File "/home/kk_gorbee/Documents/project/WirelessSensorTrackingSystem/proj/jsonSenderAndReceiver.py", line 43, in receive_message
    conn, addr = server_socket.accept()
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kk_gorbee/Documents/project/WirelessSensorTrackingSystem/proj/jsonSenderAndReceiver.py", line 43, in receive_message
    conn, addr = server_socket.accept()
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socket.py", line 294, in accept
    fd, addr = self._accept()
               ^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socket.py", line 294, in accept
    fd, addr = self._accept()
               ^^^^^^^^^^^^^^
KeyboardInterrupt
KeyboardInterrupt
------receiver of 5 is running-------- 
Got connection from ('127.0.0.1', 47788)
U************ fucking zero detected ! 
Received message from client: {}
------receiver of 3 is running-------- 
Got connection from ('127.0.0.1', 54046)
U************ fucking zero detected ! 
Received message from client: {}
Got connection from ('127.0.0.1', 54058)
U************ fucking zero detected ! 
Received message from client: {}
Got connection from ('127.0.0.1', 54066)
U************ fucking zero detected ! 
Received message from client: {}
Process Process-6:
  File "/home/kk_gorbee/Documents/project/WirelessSensorTrackingSystem/proj/jsonSenderAndReceiver.py", line 23, in sending_message
    client_socket.connect((host, port))
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kk_gorbee/Documents/project/WirelessSensorTrackingSystem/proj/jsonSenderAndReceiver.py", line 23, in sending_message
    client_socket.connect((host, port))
  File "/usr/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
ConnectionRefusedError: [Errno 111] Connection refused
  File "/usr/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kk_gorbee/Documents/project/WirelessSensorTrackingSystem/proj/./main.py", line 253, in sensor
    messenger.sending_message({0: [[], {}]}, socket.gethostname(), 19000 + neg)
  File "/home/kk_gorbee/Documents/project/WirelessSensorTrackingSystem/proj/jsonSenderAndReceiver.py", line 32, in sending_message
    time.sleep(1)
KeyboardInterrupt
Process Process-5:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kk_gorbee/Documents/project/WirelessSensorTrackingSystem/proj/jsonSenderAndReceiver.py", line 23, in sending_message
    client_socket.connect((host, port))
ConnectionRefusedError: [Errno 111] Connection refused
46 some one want to update me like that 5 , [] og state : {}
Connection refused. Retrying in 1 second...
sender send message :  {0: [[], {}]}
46 some one want to update me like that 3 , [] og state : {5: []}
sender send message :  {0: [[], {}]}
46 some one want to update me like that 1 , [] og state : {5: [], 3: []}
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Process Process-3:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kk_gorbee/Documents/project/WirelessSensorTrackingSystem/proj/./main.py", line 253, in sensor
    messenger.sending_message({0: [[], {}]}, socket.gethostname(), 19000 + neg)
  File "/home/kk_gorbee/Documents/project/WirelessSensorTrackingSystem/proj/jsonSenderAndReceiver.py", line 32, in sending_message
    time.sleep(1)
KeyboardInterrupt
  File "/usr/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kk_gorbee/Documents/project/WirelessSensorTrackingSystem/proj/./main.py", line 253, in sensor
    messenger.sending_message({0: [[], {}]}, socket.gethostname(), 19000 + neg)
  File "/home/kk_gorbee/Documents/project/WirelessSensorTrackingSystem/proj/jsonSenderAndReceiver.py", line 32, in sending_message
    time.sleep(1)
KeyboardInterrupt
46 some one want to update me like that 2 , [] og state : {}
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Traceback (most recent call last):
46 some one want to update me like that 3 , [] og state : {}
Connection refused. Retrying in 1 second...
sender send message :  {0: [[], {}]}
46 some one want to update me like that 1 , [] og state : {3: []}
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/kk_gorbee/Documents/project/WirelessSensorTrackingSystem/proj/jsonSenderAndReceiver.py", line 23, in sending_message
    client_socket.connect((host, port))
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kk_gorbee/Documents/project/WirelessSensorTrackingSystem/proj/jsonSenderAndReceiver.py", line 23, in sending_message
    client_socket.connect((host, port))
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kk_gorbee/Documents/project/WirelessSensorTrackingSystem/proj/./main.py", line 253, in sensor
    messenger.sending_message({0: [[], {}]}, socket.gethostname(), 19000 + neg)
  File "/home/kk_gorbee/Documents/project/WirelessSensorTrackingSystem/proj/jsonSenderAndReceiver.py", line 32, in sending_message
    time.sleep(1)
KeyboardInterrupt
  File "/usr/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kk_gorbee/Documents/project/WirelessSensorTrackingSystem/proj/./main.py", line 253, in sensor
    messenger.sending_message({0: [[], {}]}, socket.gethostname(), 19000 + neg)
  File "/home/kk_gorbee/Documents/project/WirelessSensorTrackingSystem/proj/jsonSenderAndReceiver.py", line 23, in sending_message
    client_socket.connect((host, port))
  File "/home/kk_gorbee/Documents/project/WirelessSensorTrackingSystem/proj/jsonSenderAndReceiver.py", line 32, in sending_message
    time.sleep(1)
KeyboardInterrupt
ConnectionRefusedError: [Errno 111] Connection refused
46 some one want to update me like that 1 , [] og state : {}
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
46 some one want to update me like that 3 , [] og state : {}
Connection refused. Retrying in 1 second...
sender send message :  {0: [[], {}]}
46 some one want to update me like that 4 , [] og state : {3: []}
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
  File "/usr/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kk_gorbee/Documents/project/WirelessSensorTrackingSystem/proj/./main.py", line 253, in sensor
    messenger.sending_message({0: [[], {}]}, socket.gethostname(), 19000 + neg)
  File "/home/kk_gorbee/Documents/project/WirelessSensorTrackingSystem/proj/jsonSenderAndReceiver.py", line 32, in sending_message
    time.sleep(1)
KeyboardInterrupt
46 some one want to update me like that 2 , [] og state : {}
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
Connection refused. Retrying in 1 second...
